// <auto-generated />
using System;
using AppChat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AppChat.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251115135324_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppChat.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("LastMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastMessageTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UnreadCount")
                        .HasColumnType("integer");

                    b.Property<int>("UserAId")
                        .HasColumnType("integer");

                    b.Property<int>("UserBId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastMessage = "Gặp sau nha 👋",
                            LastMessageTime = new DateTime(2025, 10, 28, 10, 44, 0, 0, DateTimeKind.Utc),
                            UnreadCount = 0,
                            UserAId = 1,
                            UserBId = 2
                        },
                        new
                        {
                            Id = 2,
                            LastMessage = "Ok mai gặp!",
                            LastMessageTime = new DateTime(2025, 10, 27, 21, 27, 0, 0, DateTimeKind.Utc),
                            UnreadCount = 0,
                            UserAId = 1,
                            UserBId = 3
                        },
                        new
                        {
                            Id = 3,
                            LastMessage = "Đi xem phim nhé 🎬",
                            LastMessageTime = new DateTime(2025, 10, 26, 20, 16, 0, 0, DateTimeKind.Utc),
                            UnreadCount = 0,
                            UserAId = 1,
                            UserBId = 4
                        },
                        new
                        {
                            Id = 4,
                            LastMessage = "Gửi file rồi đó!",
                            LastMessageTime = new DateTime(2025, 10, 25, 18, 20, 0, 0, DateTimeKind.Utc),
                            UnreadCount = 0,
                            UserAId = 1,
                            UserBId = 5
                        },
                        new
                        {
                            Id = 5,
                            LastMessage = "Cảm ơn nha 😁",
                            LastMessageTime = new DateTime(2025, 10, 25, 19, 24, 0, 0, DateTimeKind.Utc),
                            UnreadCount = 1,
                            UserAId = 2,
                            UserBId = 6
                        },
                        new
                        {
                            Id = 6,
                            LastMessage = "Tối nhớ học bài 😆",
                            LastMessageTime = new DateTime(2025, 10, 28, 8, 14, 0, 0, DateTimeKind.Utc),
                            UnreadCount = 0,
                            UserAId = 3,
                            UserBId = 7
                        },
                        new
                        {
                            Id = 7,
                            LastMessage = "Mai gặp nhé 💕",
                            LastMessageTime = new DateTime(2025, 10, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            UnreadCount = 0,
                            UserAId = 4,
                            UserBId = 8
                        },
                        new
                        {
                            Id = 8,
                            LastMessage = "Haha vui quá 😁",
                            LastMessageTime = new DateTime(2025, 10, 27, 18, 45, 0, 0, DateTimeKind.Utc),
                            UnreadCount = 0,
                            UserAId = 5,
                            UserBId = 7
                        },
                        new
                        {
                            Id = 9,
                            LastMessage = "Ok bro 😎",
                            LastMessageTime = new DateTime(2025, 10, 28, 22, 15, 0, 0, DateTimeKind.Utc),
                            UnreadCount = 0,
                            UserAId = 6,
                            UserBId = 8
                        },
                        new
                        {
                            Id = 10,
                            LastMessage = "Đi học thôi!",
                            LastMessageTime = new DateTime(2025, 10, 28, 9, 18, 0, 0, DateTimeKind.Utc),
                            UnreadCount = 0,
                            UserAId = 2,
                            UserBId = 5
                        });
                });

            modelBuilder.Entity("AppChat.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserIdContactA")
                        .HasColumnType("integer");

                    b.Property<int>("UserIdContactB")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserIdContactA = 1,
                            UserIdContactB = 2
                        },
                        new
                        {
                            Id = 2,
                            UserIdContactA = 1,
                            UserIdContactB = 3
                        },
                        new
                        {
                            Id = 3,
                            UserIdContactA = 1,
                            UserIdContactB = 4
                        },
                        new
                        {
                            Id = 4,
                            UserIdContactA = 1,
                            UserIdContactB = 5
                        },
                        new
                        {
                            Id = 5,
                            UserIdContactA = 1,
                            UserIdContactB = 6
                        },
                        new
                        {
                            Id = 6,
                            UserIdContactA = 1,
                            UserIdContactB = 7
                        },
                        new
                        {
                            Id = 7,
                            UserIdContactA = 1,
                            UserIdContactB = 8
                        },
                        new
                        {
                            Id = 8,
                            UserIdContactA = 2,
                            UserIdContactB = 3
                        },
                        new
                        {
                            Id = 9,
                            UserIdContactA = 2,
                            UserIdContactB = 5
                        },
                        new
                        {
                            Id = 10,
                            UserIdContactA = 2,
                            UserIdContactB = 6
                        },
                        new
                        {
                            Id = 11,
                            UserIdContactA = 2,
                            UserIdContactB = 7
                        },
                        new
                        {
                            Id = 12,
                            UserIdContactA = 3,
                            UserIdContactB = 4
                        },
                        new
                        {
                            Id = 13,
                            UserIdContactA = 3,
                            UserIdContactB = 7
                        },
                        new
                        {
                            Id = 14,
                            UserIdContactA = 3,
                            UserIdContactB = 8
                        },
                        new
                        {
                            Id = 15,
                            UserIdContactA = 4,
                            UserIdContactB = 5
                        },
                        new
                        {
                            Id = 16,
                            UserIdContactA = 4,
                            UserIdContactB = 6
                        },
                        new
                        {
                            Id = 17,
                            UserIdContactA = 4,
                            UserIdContactB = 8
                        },
                        new
                        {
                            Id = 18,
                            UserIdContactA = 5,
                            UserIdContactB = 7
                        },
                        new
                        {
                            Id = 19,
                            UserIdContactA = 6,
                            UserIdContactB = 8
                        },
                        new
                        {
                            Id = 20,
                            UserIdContactA = 7,
                            UserIdContactB = 8
                        });
                });

            modelBuilder.Entity("AppChat.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChatId = 1,
                            Content = "Chào Phuc, hôm nay rảnh không?",
                            SenderId = 1,
                            SentAt = new DateTime(2025, 10, 25, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 2,
                            ChatId = 1,
                            Content = "Rảnh nè, đi uống cà phê không ☕",
                            SenderId = 2,
                            SentAt = new DateTime(2025, 10, 25, 9, 5, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 3,
                            ChatId = 1,
                            Content = "Ok, quán cũ nha!",
                            SenderId = 1,
                            SentAt = new DateTime(2025, 10, 25, 9, 10, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 4,
                            ChatId = 1,
                            Content = "Tới luôn 😁",
                            SenderId = 2,
                            SentAt = new DateTime(2025, 10, 25, 9, 15, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 5,
                            ChatId = 1,
                            Content = "Đang đi nè 🚶‍♂️",
                            SenderId = 1,
                            SentAt = new DateTime(2025, 10, 25, 9, 20, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 6,
                            ChatId = 1,
                            Content = "Tới rồi nha",
                            SenderId = 2,
                            SentAt = new DateTime(2025, 10, 25, 9, 25, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 7,
                            ChatId = 1,
                            Content = "Thấy rồi 👋",
                            SenderId = 1,
                            SentAt = new DateTime(2025, 10, 25, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 8,
                            ChatId = 1,
                            Content = "Uống gì đây?",
                            SenderId = 2,
                            SentAt = new DateTime(2025, 10, 25, 9, 35, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 9,
                            ChatId = 1,
                            Content = "Cho ly đen đá 😆",
                            SenderId = 1,
                            SentAt = new DateTime(2025, 10, 25, 9, 40, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 10,
                            ChatId = 2,
                            Content = "Khoa ơi, API chạy chưa?",
                            SenderId = 3,
                            SentAt = new DateTime(2025, 10, 26, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 11,
                            ChatId = 2,
                            Content = "Chạy rồi, đang test thêm chút!",
                            SenderId = 1,
                            SentAt = new DateTime(2025, 10, 26, 9, 5, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 12,
                            ChatId = 2,
                            Content = "Good job 💪",
                            SenderId = 3,
                            SentAt = new DateTime(2025, 10, 26, 9, 10, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 13,
                            ChatId = 2,
                            Content = "Cảm ơn nhé 😎",
                            SenderId = 1,
                            SentAt = new DateTime(2025, 10, 26, 9, 15, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 14,
                            ChatId = 2,
                            Content = "Mai review nha",
                            SenderId = 3,
                            SentAt = new DateTime(2025, 10, 26, 9, 20, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 15,
                            ChatId = 2,
                            Content = "Ok deal!",
                            SenderId = 1,
                            SentAt = new DateTime(2025, 10, 26, 9, 25, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 16,
                            ChatId = 2,
                            Content = "Nhớ đem laptop 😅",
                            SenderId = 3,
                            SentAt = new DateTime(2025, 10, 26, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 17,
                            ChatId = 2,
                            Content = "Haha tất nhiên rồi",
                            SenderId = 1,
                            SentAt = new DateTime(2025, 10, 26, 9, 35, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 18,
                            ChatId = 2,
                            Content = "Ok, gặp sáng mai nhé 👋",
                            SenderId = 3,
                            SentAt = new DateTime(2025, 10, 26, 9, 40, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 19,
                            ChatId = 3,
                            Content = "Cuối tuần đi xem phim nhé 🎬",
                            SenderId = 4,
                            SentAt = new DateTime(2025, 10, 26, 20, 0, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 20,
                            ChatId = 3,
                            Content = "Phim gì vậy?",
                            SenderId = 1,
                            SentAt = new DateTime(2025, 10, 26, 20, 5, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 21,
                            ChatId = 3,
                            Content = "Marvel mới ra đó 😁",
                            SenderId = 4,
                            SentAt = new DateTime(2025, 10, 26, 20, 10, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 22,
                            ChatId = 3,
                            Content = "Ok, đặt vé nhé",
                            SenderId = 1,
                            SentAt = new DateTime(2025, 10, 26, 20, 15, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 23,
                            ChatId = 3,
                            Content = "Đặt 2 vé rồi nha ❤️",
                            SenderId = 4,
                            SentAt = new DateTime(2025, 10, 26, 20, 20, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 24,
                            ChatId = 3,
                            Content = "Nice! hẹn gặp 😄",
                            SenderId = 1,
                            SentAt = new DateTime(2025, 10, 26, 20, 25, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 25,
                            ChatId = 3,
                            Content = "Mai 7h nhé!",
                            SenderId = 4,
                            SentAt = new DateTime(2025, 10, 26, 20, 30, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 26,
                            ChatId = 3,
                            Content = "Okeee 😎",
                            SenderId = 1,
                            SentAt = new DateTime(2025, 10, 26, 20, 35, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 27,
                            ChatId = 3,
                            Content = "Ngủ sớm nha 😆",
                            SenderId = 4,
                            SentAt = new DateTime(2025, 10, 26, 20, 40, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 28,
                            ChatId = 4,
                            Content = "Khoa gửi tài liệu chưa?",
                            SenderId = 5,
                            SentAt = new DateTime(2025, 10, 25, 18, 0, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 29,
                            ChatId = 4,
                            Content = "Đang gửi nè 📎",
                            SenderId = 1,
                            SentAt = new DateTime(2025, 10, 25, 18, 5, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 30,
                            ChatId = 4,
                            Content = "Ok thấy rồi",
                            SenderId = 5,
                            SentAt = new DateTime(2025, 10, 25, 18, 10, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 31,
                            ChatId = 4,
                            Content = "Check giúp nha",
                            SenderId = 1,
                            SentAt = new DateTime(2025, 10, 25, 18, 15, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 32,
                            ChatId = 4,
                            Content = "Ổn hết 👍",
                            SenderId = 5,
                            SentAt = new DateTime(2025, 10, 25, 18, 20, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 33,
                            ChatId = 4,
                            Content = "Tốt quá 😁",
                            SenderId = 1,
                            SentAt = new DateTime(2025, 10, 25, 18, 25, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 34,
                            ChatId = 4,
                            Content = "Mai nộp nha",
                            SenderId = 5,
                            SentAt = new DateTime(2025, 10, 25, 18, 30, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 35,
                            ChatId = 4,
                            Content = "Ok!",
                            SenderId = 1,
                            SentAt = new DateTime(2025, 10, 25, 18, 35, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 36,
                            ChatId = 4,
                            Content = "Thanks bro 😆",
                            SenderId = 5,
                            SentAt = new DateTime(2025, 10, 25, 18, 40, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 37,
                            ChatId = 5,
                            Content = "Tuan ơi mai học môn gì nhỉ?",
                            SenderId = 2,
                            SentAt = new DateTime(2025, 10, 25, 19, 0, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 38,
                            ChatId = 5,
                            Content = "Toán cao cấp đó 😅",
                            SenderId = 6,
                            SentAt = new DateTime(2025, 10, 25, 19, 5, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 39,
                            ChatId = 5,
                            Content = "Ôi lại nữa à",
                            SenderId = 2,
                            SentAt = new DateTime(2025, 10, 25, 19, 10, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 40,
                            ChatId = 5,
                            Content = "Chuẩn bị bài kỹ nha!",
                            SenderId = 6,
                            SentAt = new DateTime(2025, 10, 25, 19, 15, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 41,
                            ChatId = 5,
                            Content = "Ok, tối nay làm bài chung nhé",
                            SenderId = 2,
                            SentAt = new DateTime(2025, 10, 25, 19, 20, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 42,
                            ChatId = 5,
                            Content = "Được luôn 😎",
                            SenderId = 6,
                            SentAt = new DateTime(2025, 10, 25, 19, 25, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 43,
                            ChatId = 5,
                            Content = "8h call nhé",
                            SenderId = 2,
                            SentAt = new DateTime(2025, 10, 25, 19, 30, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 44,
                            ChatId = 5,
                            Content = "Ok deal!",
                            SenderId = 6,
                            SentAt = new DateTime(2025, 10, 25, 19, 35, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 45,
                            ChatId = 5,
                            Content = "Cảm ơn nha 😁",
                            SenderId = 2,
                            SentAt = new DateTime(2025, 10, 25, 19, 40, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 46,
                            ChatId = 6,
                            Content = "Han ơi làm bài tập xong chưa?",
                            SenderId = 3,
                            SentAt = new DateTime(2025, 10, 27, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 47,
                            ChatId = 6,
                            Content = "Sắp xong rồi 😅",
                            SenderId = 7,
                            SentAt = new DateTime(2025, 10, 27, 8, 5, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 48,
                            ChatId = 6,
                            Content = "Cần giúp không?",
                            SenderId = 3,
                            SentAt = new DateTime(2025, 10, 27, 8, 10, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 49,
                            ChatId = 6,
                            Content = "Có chứ 😁",
                            SenderId = 7,
                            SentAt = new DateTime(2025, 10, 27, 8, 15, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 50,
                            ChatId = 6,
                            Content = "Ok để mình gọi nha",
                            SenderId = 3,
                            SentAt = new DateTime(2025, 10, 27, 8, 20, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 51,
                            ChatId = 6,
                            Content = "Cảm ơn nha 😍",
                            SenderId = 7,
                            SentAt = new DateTime(2025, 10, 27, 8, 25, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 52,
                            ChatId = 6,
                            Content = "Không có chi 😉",
                            SenderId = 3,
                            SentAt = new DateTime(2025, 10, 27, 8, 30, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 53,
                            ChatId = 6,
                            Content = "Tối gặp nhé",
                            SenderId = 7,
                            SentAt = new DateTime(2025, 10, 27, 8, 35, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 54,
                            ChatId = 6,
                            Content = "Ok luôn 😆",
                            SenderId = 3,
                            SentAt = new DateTime(2025, 10, 27, 8, 40, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 55,
                            ChatId = 7,
                            Content = "Nam ơi mai có họp nhóm không?",
                            SenderId = 4,
                            SentAt = new DateTime(2025, 10, 27, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 56,
                            ChatId = 7,
                            Content = "Có nha, 9h bắt đầu",
                            SenderId = 8,
                            SentAt = new DateTime(2025, 10, 27, 9, 5, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 57,
                            ChatId = 7,
                            Content = "Ok, chuẩn bị tài liệu nhé",
                            SenderId = 4,
                            SentAt = new DateTime(2025, 10, 27, 9, 10, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 58,
                            ChatId = 7,
                            Content = "Mình lo phần đó rồi 😎",
                            SenderId = 8,
                            SentAt = new DateTime(2025, 10, 27, 9, 15, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 59,
                            ChatId = 7,
                            Content = "Good, cảm ơn nha ❤️",
                            SenderId = 4,
                            SentAt = new DateTime(2025, 10, 27, 9, 20, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 60,
                            ChatId = 7,
                            Content = "Không có gì 😄",
                            SenderId = 8,
                            SentAt = new DateTime(2025, 10, 27, 9, 25, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 61,
                            ChatId = 7,
                            Content = "Mai gặp nhé 👋",
                            SenderId = 4,
                            SentAt = new DateTime(2025, 10, 27, 9, 30, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 62,
                            ChatId = 7,
                            Content = "See you!",
                            SenderId = 8,
                            SentAt = new DateTime(2025, 10, 27, 9, 35, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 63,
                            ChatId = 7,
                            Content = "Nhớ đem laptop nha 💻",
                            SenderId = 4,
                            SentAt = new DateTime(2025, 10, 27, 9, 40, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 64,
                            ChatId = 8,
                            Content = "Han ơi bài tập nhóm sao rồi?",
                            SenderId = 5,
                            SentAt = new DateTime(2025, 10, 27, 18, 0, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 65,
                            ChatId = 8,
                            Content = "Gần xong rồi 😁",
                            SenderId = 7,
                            SentAt = new DateTime(2025, 10, 27, 18, 5, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 66,
                            ChatId = 8,
                            Content = "Cần mình giúp gì không?",
                            SenderId = 5,
                            SentAt = new DateTime(2025, 10, 27, 18, 10, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 67,
                            ChatId = 8,
                            Content = "Ok gửi phần cậu qua nhé",
                            SenderId = 7,
                            SentAt = new DateTime(2025, 10, 27, 18, 15, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 68,
                            ChatId = 8,
                            Content = "Gửi rồi đó",
                            SenderId = 5,
                            SentAt = new DateTime(2025, 10, 27, 18, 20, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 69,
                            ChatId = 8,
                            Content = "Nhận được rồi ✅",
                            SenderId = 7,
                            SentAt = new DateTime(2025, 10, 27, 18, 25, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 70,
                            ChatId = 8,
                            Content = "Tối call nhé",
                            SenderId = 5,
                            SentAt = new DateTime(2025, 10, 27, 18, 30, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 71,
                            ChatId = 8,
                            Content = "Ok deal 😆",
                            SenderId = 7,
                            SentAt = new DateTime(2025, 10, 27, 18, 35, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 72,
                            ChatId = 8,
                            Content = "Cảm ơn nha",
                            SenderId = 5,
                            SentAt = new DateTime(2025, 10, 27, 18, 40, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 73,
                            ChatId = 9,
                            Content = "Nam ơi tối chơi game không?",
                            SenderId = 6,
                            SentAt = new DateTime(2025, 10, 28, 21, 0, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 74,
                            ChatId = 9,
                            Content = "Có luôn bro 😎",
                            SenderId = 8,
                            SentAt = new DateTime(2025, 10, 28, 21, 5, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 75,
                            ChatId = 9,
                            Content = "Rank hay thường?",
                            SenderId = 6,
                            SentAt = new DateTime(2025, 10, 28, 21, 10, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 76,
                            ChatId = 9,
                            Content = "Rank chứ 😁",
                            SenderId = 8,
                            SentAt = new DateTime(2025, 10, 28, 21, 15, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 77,
                            ChatId = 9,
                            Content = "Ok vào phòng nhé",
                            SenderId = 6,
                            SentAt = new DateTime(2025, 10, 28, 21, 20, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 78,
                            ChatId = 9,
                            Content = "Tới liền 🔥",
                            SenderId = 8,
                            SentAt = new DateTime(2025, 10, 28, 21, 25, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 79,
                            ChatId = 9,
                            Content = "GG ez 😆",
                            SenderId = 6,
                            SentAt = new DateTime(2025, 10, 28, 21, 30, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 80,
                            ChatId = 9,
                            Content = "Haha vui quá 😂",
                            SenderId = 8,
                            SentAt = new DateTime(2025, 10, 28, 21, 35, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 81,
                            ChatId = 9,
                            Content = "Mai nữa nha!",
                            SenderId = 6,
                            SentAt = new DateTime(2025, 10, 28, 21, 40, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 82,
                            ChatId = 10,
                            Content = "Bao ơi đi học chưa?",
                            SenderId = 2,
                            SentAt = new DateTime(2025, 10, 28, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 83,
                            ChatId = 10,
                            Content = "Sắp tới rồi 😆",
                            SenderId = 5,
                            SentAt = new DateTime(2025, 10, 28, 8, 5, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 84,
                            ChatId = 10,
                            Content = "Nhớ mang slide nha",
                            SenderId = 2,
                            SentAt = new DateTime(2025, 10, 28, 8, 10, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 85,
                            ChatId = 10,
                            Content = "Ok mình in rồi ✅",
                            SenderId = 5,
                            SentAt = new DateTime(2025, 10, 28, 8, 15, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 86,
                            ChatId = 10,
                            Content = "Tốt quá!",
                            SenderId = 2,
                            SentAt = new DateTime(2025, 10, 28, 8, 20, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 87,
                            ChatId = 10,
                            Content = "Hẹn ở lớp nha",
                            SenderId = 5,
                            SentAt = new DateTime(2025, 10, 28, 8, 25, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 88,
                            ChatId = 10,
                            Content = "Ok đi liền đây 🚶‍♂️",
                            SenderId = 2,
                            SentAt = new DateTime(2025, 10, 28, 8, 30, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 89,
                            ChatId = 10,
                            Content = "Thấy rồi 👋",
                            SenderId = 5,
                            SentAt = new DateTime(2025, 10, 28, 8, 35, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        },
                        new
                        {
                            Id = 90,
                            ChatId = 10,
                            Content = "Đi học thôi 😁",
                            SenderId = 2,
                            SentAt = new DateTime(2025, 10, 28, 8, 40, 0, 0, DateTimeKind.Utc),
                            Status = ""
                        });
                });

            modelBuilder.Entity("AppChat.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "",
                            FirstName = "Dang",
                            IsOnline = true,
                            LastName = "Khoa",
                            LastSeen = new DateTime(2025, 11, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            PhoneNumber = "0901000001"
                        },
                        new
                        {
                            Id = 2,
                            AvatarUrl = "",
                            FirstName = "Minh",
                            IsOnline = false,
                            LastName = "Phuc",
                            LastSeen = new DateTime(2025, 11, 3, 11, 55, 0, 0, DateTimeKind.Utc),
                            PhoneNumber = "0901000002"
                        },
                        new
                        {
                            Id = 3,
                            AvatarUrl = "",
                            FirstName = "Hai",
                            IsOnline = false,
                            LastName = "Dang",
                            LastSeen = new DateTime(2025, 11, 3, 11, 50, 0, 0, DateTimeKind.Utc),
                            PhoneNumber = "0901000003"
                        },
                        new
                        {
                            Id = 4,
                            AvatarUrl = "",
                            FirstName = "Thao",
                            IsOnline = true,
                            LastName = "Nguyen",
                            LastSeen = new DateTime(2025, 11, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            PhoneNumber = "0901000004"
                        },
                        new
                        {
                            Id = 5,
                            AvatarUrl = "",
                            FirstName = "Bao",
                            IsOnline = false,
                            LastName = "Tran",
                            LastSeen = new DateTime(2025, 11, 3, 11, 0, 0, 0, DateTimeKind.Utc),
                            PhoneNumber = "0901000005"
                        },
                        new
                        {
                            Id = 6,
                            AvatarUrl = "",
                            FirstName = "Anh",
                            IsOnline = true,
                            LastName = "Tuan",
                            LastSeen = new DateTime(2025, 11, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            PhoneNumber = "0901000006"
                        },
                        new
                        {
                            Id = 7,
                            AvatarUrl = "",
                            FirstName = "Ngoc",
                            IsOnline = false,
                            LastName = "Han",
                            LastSeen = new DateTime(2025, 11, 3, 11, 30, 0, 0, DateTimeKind.Utc),
                            PhoneNumber = "0901000007"
                        },
                        new
                        {
                            Id = 8,
                            AvatarUrl = "",
                            FirstName = "Le",
                            IsOnline = false,
                            LastName = "Nam",
                            LastSeen = new DateTime(2025, 11, 3, 11, 45, 0, 0, DateTimeKind.Utc),
                            PhoneNumber = "0901000008"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
